# Generated by Django 2.2 on 2024-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsPortal', '0004_result_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualresult',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_result_data',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
