# Generated by Django 2.2 on 2024-02-01 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentsPortal', '0003_annualresult_annualstudent_result_student_result_data_students_pin_and_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='None', max_length=200)),
                ('LastName', models.CharField(blank=True, default='None', max_length=200)),
                ('Phone_number', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('teachers_id', models.CharField(blank=True, max_length=200)),
                ('Role', models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Formteacher', 'Formteacher'), ('Admin', 'Admin')], default='Teacher', max_length=200)),
                ('Headshot', models.ImageField(blank=True, upload_to='assets/TeachersProfileimages')),
                ('classFormed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentsPortal.Class')),
                ('classes_taught', models.ManyToManyField(related_name='assigned_classes', to='StudentsPortal.Class')),
                ('subjects_taught', models.ManyToManyField(to='StudentsPortal.Subject')),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
