# Generated by Django 2.2 on 2024-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0002_auto_20240509_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, related_name='assigned_classes', to='StudentsPortal.Class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='assigned_subjects', to='StudentsPortal.Subject'),
        ),
    ]
