# Generated by Django 2.2 on 2024-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeachersPortal', '0003_auto_20240510_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='FirstName',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='LastName',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
